---
- hosts: all
  user: root
  become: yes
  tasks:
   
    - name: install java
      yum:
        name: java
        state: present

    - name: directory creation
      file:
        path: /root/tomcat
        state: directory

    - name: download & unarchive tomcat9 
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz
        dest: /root/tomcat
        remote_src: yes

    - name: Run Tomcat
      shell: nohup ./startup.sh
      args:
        chdir: /root/tomcat/apache-tomcat-9.0.83/bin      

    




             
